### ISSUE TITLE
An exception causes bad sql to be generated

### ISSUE THREAD

**Issue by ddispaltro** [okumin/akka-persistence-sql-async#10]
If you throw an exception in a persistentActor there seems to be a chance that `asyncWriteMessages` will be handed a empty sequence of atomicwrites, in which case the sql generated is invalid. The leveldb doesn't batch like this journal impl, so it doesn't suffer from the same issue.

Should be a simple fix.

**Comment by ddispaltro** [comment]
I stumbled upon the same issue in another journal, dnvriend/akka-persistence-jdbc#27

**Comment by okumin** [comment]
Thanks for your reporting, and I have confirmed that error.

**Comment by okumin** [comment]
Publish a new fixed version.
https://github.com/okumin/akka-persistence-sql-async/releases/tag/v0.3.1

Thanks!
