### ISSUE TITLE
Help for migration

### ISSUE THREAD

**Issue by Kevin-Lee** [okumin/akka-persistence-sql-async#11]
Hi,

I'm just wondering if there is any guide to migrate from 0.2.x to 0.3.1.
To be more specific, my concern is the `sequence_nr` column in the metadata table. Is it the biggest sequence number from the journal table?

**Comment by okumin** [comment]
@Kevin-Lee 
There is no guide.

> To be more specific, my concern is the sequence_nr column in the metadata table. Is it the biggest sequence number from the journal table?

Yes.
It is always OK if you set the highest sequence number of the journal table.

**Comment by Kevin-Lee** [comment]
@okumin OK, good! Thank you. :smile:
