### ISSUE TITLE
Don't swallow journal serialization errors.

### ISSUE THREAD

**Issue by ds300** [okumin/akka-persistence-sql-async#16]
If serializers fail for some reason, the error is simply ignored. This is whack behaviour.

Here is the culprit: https://github.com/okumin/akka-persistence-sql-async/blob/b7d468a44c0023bd8f3aec0a6fcd1f897b1d862c/core/src/main/scala/akka/persistence/journal/sqlasync/ScalikeJDBCWriteJournal.scala#L32

This `collect` filters out failures.

This also seems to result in the `$batch` expression on line 53 evaluating to the empty string when `result` contains only failures, producing invalid SQL syntax.

It would be super nice to get some proper error handling in here, or at least logging the cause exception to stderr.

**Comment by lbialy** [comment]
Do you think serialization error should fail wrapping future?

**Comment by ds300** [comment]
What I think should happen is that the cause stack trace should be logged to stderr and the resulting SQL should not be executed.

**Comment by okumin** [comment]
I think that it fails……

**Comment by lbialy** [comment]
Apparently reference implementation for LevelDB catches serialization exceptions in [Try monad](https://github.com/akka/akka/blob/master/akka-persistence/src/main/scala/akka/persistence/journal/leveldb/LeveldbStore.scala#L57-L74) but doesnt perform `collect { Success() }` on resulting collection of `Try`s.

**Comment by okumin** [comment]
Such a error should be notified to PersistentActor since journals don't work if some of them silently fails.

**Comment by okumin** [comment]
I remember that serialization errors can be rejected.
http://doc.akka.io/docs/akka/2.4/scala/persistence.html#Journal_plugin_API

I'm thinking to apply the following patches.

- Not executing when all the payload cannot be serialized
- Logging when a serialization error occurs
    - This is for convenience
    - Users who want to handle such an error can use [onPersistRejected](http://doc.akka.io/docs/akka/2.4/scala/persistence.html#Persistence_status_handling).

**Comment by lbialy** [comment]
:+1:

**Comment by okumin** [comment]
I close this issue since it looks that the above solution is accepted.

The patch is already applied.
https://github.com/okumin/akka-persistence-sql-async/commit/2c449c5098a484ea24580d65948bbf25845548bd

Thanks.
