### ISSUE TITLE
Support for multiple Database configurations

### ISSUE THREAD

**Issue by justinhj** [okumin/akka-persistence-sql-async#20]
Is there any way to achieve the following?

Use akka-persistence-sql-async for two kinds of persistent actor
One type is in mysql database A and the other is in mysql database B
They require different configuration details.

**Comment by okumin** [comment]
@justinhj You mean that you want to select the database for a particular PersistentActor, right?
That needs a logic to select a connection at run-time and I have no good idea.

**Comment by justinhj** [comment]
Ok thanks, just checking I wasn't missing some obvious way of doing it.
