### ISSUE TITLE
Update homepage table instructions

### ISSUE THREAD

**Issue by Akrome** [okumin/akka-persistence-sql-async#23]
Hi.

The table creation scripts on the doc specify the use of BLOB for snapshots and journal.

Mysql's default max size for BLOB is 65k. Mysql default is also to not enable strict mode. This mean that writing more than that as a blob truncates it "silently" (an alert should be raised, but nothing was in my logs, could be my configuration, unsure), failing on recovery.

Maybe add a caveat about using MEDIUMBLOB (50Mb max) upon planning to store a lot in a snapshot.

**Comment by okumin** [comment]
@Akrome Modified BLOB into LONGBLOB.
https://github.com/okumin/akka-persistence-sql-async/commit/1e72fb96d408838d71e8e38a14a855de19a13432

Thanks for your pointing.
