### ISSUE TITLE
Publish for Scala 2.12

### ISSUE THREAD

**Issue by nitrogenice** [okumin/akka-persistence-sql-async#28]
Hi,

I am trying to use this library as a backend for my akka app, which is based on Scala 2.12. Would it be possible to publish this repository for Scala 2.12?

Best,
Hyun Min

**Comment by okumin** [comment]
@nitrogenice Published v0.5.0 which supports Scala 2.12.
https://github.com/okumin/akka-persistence-sql-async/releases/tag/v0.5.0

Thanks!
