### ISSUE TITLE
Publish version 0.1.1 for password

### ISSUE THREAD

**Issue by tenorviol** [okumin/akka-persistence-sql-async#4]
You changed the `pass` configuration to `password` here https://github.com/okumin/akka-persistence-sql-async/commit/5c9d964a33a3c7370922928107c9ac41c88476c3#diff-a4441f1c142401995aaa7a4923038bab and that looks like a good change. But the currently published maven version contains the `pass` version. Perhaps you could release a 0.1.1 version with this change?

**Comment by okumin** [comment]
Finished to publish v0.2 release.
https://github.com/okumin/akka-persistence-sql-async/releases/tag/v0.2

Thanks!
